- src/sqlalchemy_cratedb/__init__.py
- src/sqlalchemy_cratedb/compiler.py
- src/sqlalchemy_cratedb/dialect.py
- src/sqlalchemy_cratedb/type/__init__.py
- src/sqlalchemy_cratedb/type/array.py
- src/sqlalchemy_cratedb/type/geo.py
- src/sqlalchemy_cratedb/type/object.py
- tests/compiler_test.py
- tests/dialect_test.py
- tests/query_caching.py
- tests/warnings_test.py
As we will add more type implementations, putting each one into a separate file will help us to have a better overview and explorability, and may also support when swapping corresponding implementations for evaluation purposes.
The patch doesn't change any code, it just moves it around.
> [TYPES] Refactor data type implementations to use their own file each

- pyproject.toml
Need to downgrade pandas, which is used for testing.
```python
ImportError: cannot import name 'makeTimeDataFrame' from 'pandas._testing'
```
> Chore: Fix pandas testing dependency by downgrading to pandas 2.0

- .github/workflows/codeql.yml
This reverts commit 2cc91474c179418d34fcd72ad61df8f88f9e01c6.
CodeQL checks started failing [^1], maybe because of GH-2?
[^1]: https://github.com/crate-workbench/sqlalchemy-cratedb/actions/runs/7615862437/job/20828562756?pr=30
> Revert "Bump github/codeql-action from 2 to 3"

- .github/workflows/tests.yml
`codecov-action@v4` has issues, it apparently does not upload without token any longer.
This reverts commit 45735bd1a7eb0aa508d9f5b830424a3e880d429a.
- GH-36
> Revert "Bump codecov/codecov-action from 3 to 4"

- CHANGES.md
- pyproject.toml
```
ImportError: Dask dataframe requirements are not installed.
```
-- https://github.com/crate-workbench/sqlalchemy-cratedb/actions/runs/8424937102/job/23069945255?pr=50#step:6:537
- https://github.com/crate-workbench/cratedb-toolkit/pull/128
- https://github.com/crate-workbench/sqlalchemy-cratedb/pull/49
- https://github.com/crate-workbench/sqlalchemy-cratedb/pull/50
> Dependencies: Use `dask[dataframe]`

- .github/workflows/tests.yml
> Tokenless uploading is unsupported. However, PRs made from forks to
> the upstream public repos will support tokenless (e.g. contributors to
> OS projects do not need the upstream repo's Codecov token). This doc
> shows instructions on how to add the Codecov token.
>
> -- https://docs.codecov.com/docs/adding-the-codecov-token#github-actions
- https://github.com/crate-workbench/mlflow-cratedb/pull/103
- https://github.com/crate-workbench/cratedb-toolkit/pull/116
> CI: Update to codecov-action@v4

- .github/workflows/release.yml
- CHANGES.md
- docs/install.rst
- pyproject.toml
- src/sqlalchemy_cratedb/__init__.py
- src/sqlalchemy_cratedb/dialect.py
- tests/__init__.py
- tests/compiler_test.py
Another few maintenance adjustments in the spirit of GH-66.
Those are aftermath fixes, and intended to be included into an initial release of this package, before adding any other features.
Along the lines, 5d274c3358a also updates the CI/GHA job for staging release packages to PyPI.
> Chore: Fix package entrypoint and module imports after migration from crate-python

- CHANGES.md
- pyproject.toml
Better pinning it here instead of polluting downstream projects. This version of `crate-python` has been stripped off the SQLAlchemy code, because it lives here now.
> Dependencies: Use `crate==1.0.0dev0`

- .github/workflows/nightly.yml
- .github/workflows/tests.yml
- CHANGES.md
- DEVELOP.md
- bootstrap.sh
- docs/data-types.rst
- docs/index.rst
- docs/working-with-types.rst
- pyproject.toml
- src/sqlalchemy_cratedb/__init__.py
- src/sqlalchemy_cratedb/compiler.py
- src/sqlalchemy_cratedb/dialect.py
- src/sqlalchemy_cratedb/type/__init__.py
- src/sqlalchemy_cratedb/type/vector.py
- tests/compiler_test.py
- tests/integration.py
- tests/vector_test.py
CrateDB's [`FLOAT_VECTOR`](https://crate.io/docs/crate/reference/en/latest/general/ddl/data-types.html#float-vector) data type, and its accompanying [`KNN_MATCH`](https://cratedb.com/docs/crate/reference/en/latest/general/builtins/scalar-functions.html#scalar-knn-match) function, have been added with CrateDB 5.5.0. This patch adds corresponding SQLAlchemy type and function/predicate support.
Those two implementetations have been predecessors, and both sites will be used to verify this patch, after it has been merged.
- [LangChain Vector Store: vectorstores/cratedb/sqlalchemy_type.py](https://github.com/crate-workbench/langchain/blob/0a831a6/libs/langchain/langchain/vectorstores/cratedb/sqlalchemy_type.py)
- [Meltano CrateDB Target: …
> Types: Add support for CrateDB's `FLOAT_VECTOR` data type and `KNN_MATCH` function

- CHANGES.md
- pyproject.toml
- src/sqlalchemy_cratedb/dialect.py
- tests/compiler_test.py
- tests/conftest.py
- tests/datetime_test.py
- tests/dict_test.py
- tests/insert_from_select_test.py
- tests/test_schema.py
- tests/update_test.py
The `get_table_names()` reflection method did not respect the `schema` query argument in SQLAlchemy connection URLs.
This improvement has been used successfully on a few downstream projects and is known as [the inspector patch](https://github.com/crate-workbench/cratedb-toolkit/blob/v0.0.2/cratedb_toolkit/sqlalchemy/patch.py). This patch brings it to mainline. 
- https://github.com/crate-workbench/cratedb-toolkit/pull/59
> Dialect: Fix `get_table_names()` reflection method

- tests/insert_from_select_test.py
GitHub/CodeQL code quality security scanning raised an admonition, `py/import-of-mutable-attribute`, at this spot:
https://github.com/crate-workbench/sqlalchemy-cratedb/blob/3c58403a4c8ffa18601190dac80ba15b675342ae/tests/insert_from_select_test.py#L26-L26
> Importing the value of 'select' from means that any change made to will be not be observed locally. 
- https://github.com/crate-workbench/sqlalchemy-cratedb/security/code-scanning/89
> Chore: Fix "Importing value of mutable attribute" in test case

- .github/workflows/docs.yml
- .gitignore
- CHANGES.md
- README.md
- bootstrap.sh
- docs/Makefile
- docs/_extra/robots.txt
- docs/advanced-querying.rst
- docs/build.json
- docs/conf.py
- docs/data-types.rst
- docs/dataframe.rst
- docs/index-all.rst
- docs/index.rst
- docs/install.rst
- docs/overview.rst
- docs/requirements.txt
- pyproject.toml
- src/sqlalchemy_cratedb/compat/api13.py
- src/sqlalchemy_cratedb/support.py
Enable project to be slotted into the documentation tree.
The documentation will be published to https://cratedb.com/docs/sqlalchemy-cratedb/.
> Documentation: Add/reactivate documentation as `sqlalchemy-cratedb`

- docs/index.rst
- docs/migrate-from-crate-client.md
In June 2024, code from the package [crate\[sqlalchemy\]] has been transferred to the package [sqlalchemy-cratedb]. For 80% of the use cases, this will be a drop-in replacement with no noticeable changes.
This patch adds a corresponding documentation section conveying a few migration notes.
https://sqlalchemy-cratedb--135.org.readthedocs.build/migrate-from-crate-client.html
[crate\[sqlalchemy\]]: https://pypi.org/project/crate/
[sqlalchemy-cratedb]: https://pypi.org/project/sqlalchemy-cratedb/
_Happy to receive an acknowledgement from anyone, to be able to continue work depending on this. Thanks!_
/cc @surister, @matriv
> Documentation: Add section about migration from `crate.client`

- CHANGES.md
- src/sqlalchemy_cratedb/compiler.py
- src/sqlalchemy_cratedb/dialect.py
- tests/compiler_test.py
By using this component of the SQLAlchemy dialect compiler, it can define CrateDB's reserved words to be quoted properly when building SQL statements.
In this case, `OBJECT` needs to be quoted when used as column name.
- https://github.com/RDFLib/rdflib-sqlalchemy/pull/106
> Compiler: Add `CrateIdentifierPreparer` for properly quoting reserved words

- CHANGES.md
- src/sqlalchemy_cratedb/dialect.py
- tests/dialect_test.py
The test suite of `meltano-tap-cratedb`, derived from the corresponding PostgreSQL adapter, will process database introspection return values by marshalling them to JSON. Because `get_pk_constraint` returns a `set` type, that will fail.
```python
TypeError: Object of type set is not JSON serializable
```
This is coming from a [monkeypatch to meltano-tap-cratedb](https://github.com/crate-workbench/meltano-tap-cratedb/blob/b1b7a6d2/tap_cratedb/patch.py#L29-L49).
> Dialect: Fix `get_pk_constraint` to return `list` instead of `set` type

- CHANGES.md
- docs/support.md
- src/sqlalchemy_cratedb/support/__init__.py
- src/sqlalchemy_cratedb/support/pandas.py
- tests/test_support_pandas.py
In certain cases where SQLAlchemy orchestration is implemented within a framework, like at this spot [^1] in pandas' `SQLTable._create_table_setup`, it is not easily possible to forward SQLAlchemy dialect options at table creation time.
Unlock SQLAlchemy ORM's `__table_args__` on the pandas/Dask `to_sql()` interface, in order to support CrateDB's special SQL DDL options.
In order to augment the SQL DDL statement to make it honor database-specific dialect options, the only way to work around the unfortunate situation is by monkey-patching the call to `sa.Table()` at runtime, relaying additional dialect options through corresponding keyword arguments in their original `<dialect>_<kwarg>` format [^2].
Using a context manager incantation like `with table_kwargs(crate_partitioned_by="time")` …
> Add `table_kwargs` context manager to make pandas/Dask support CrateDB's special SQL DDL options

- src/sqlalchemy_cratedb/support/polyfill.py
- src/sqlalchemy_cratedb/support/util.py
@seut suggested another improvement at https://github.com/crate/sqlalchemy-cratedb/pull/28#pullrequestreview-2135990302:
> I think I'd prefer moving this quoting logic into the `refresh_table`function, by change it's signature to consume an optional schema. This would avoid that it will be called with unquoted or invalid relation names.
This patch refactors the auxiliary logic into `support.util.refresh_table`, but doesn't do anything else yet, in order not to complicate the interface too quickly/early.
Maybe I am currently not seeing the spot for important improvements, which should be done right from the start: So, please advise if you still would like to introduce an optional schema name as function argument, and also please suggest further improvements you would like to see in this …
> Support: Generalize one more use case into `support.util.refresh_table`

- CHANGES.md
- src/sqlalchemy_cratedb/compiler.py
- tests/create_table_test.py
- tests/test_support_pandas.py
Configuring special table options like `crate_"translog.durability"` was not possible, because they got rendered into SQL DDL in uppercase letters. That fails like:
SQLParseException[Invalid property "TRANSLOG.DURABILITY" passed to
[ALTER | CREATE] TABLE statement]
> Fixed SQL rendering of special DDL table options in `CrateDDLCompiler`.

- CHANGES.md
- src/sqlalchemy_cratedb/compiler.py
- src/sqlalchemy_cratedb/dialect.py
- tests/create_table_test.py
- tests/datetime_test.py
- tests/update_test.py
Timezone-aware SQLAlchemy `DateTime` fields apparently are supported already. This patch just removes a corresponding assertion which prevented them from actually being used.
Originally, this is coming from a [monkeypatch to meltano-target-cratedb](https://github.com/crate-workbench/meltano-target-cratedb/blob/2b20640/target_cratedb/sqlalchemy/patch.py#L39-L51). Most probably, it is also related to those requests:
- crate/sqlalchemy-cratedb#92
- crate/crate-python#626
Other than this, that other patch is also related:
- GH-25
> Types: Unlock supporting timezone-aware `DateTime` fields

- CHANGES.md
- src/sqlalchemy_cratedb/dialect.py
- tests/datetime_test.py
The test suite of `meltano-tap-cratedb`, derived from the corresponding PostgreSQL adapter, will supply `dt.date` objects. Without this patch, those will otherwise fail on this routine.
- This is coming from a [monkeypatch to meltano-tap-cratedb](https://github.com/crate-workbench/meltano-tap-cratedb/blob/b1b7a6d2/tap_cratedb/patch.py#L10-L26).
- GH-22
> Types: Accept marshalling `datetime.date` values on `DateTime` fields

- CHANGES.md
- src/sqlalchemy_cratedb/support/__init__.py
- src/sqlalchemy_cratedb/support/util.py
- tests/test_support_util.py
The `quote_relation_name` support utility function is required in other packages than cratedb-toolkit. Because cratedb-toolkit is too heavy to be pulled into smaller packages, let's break it out of it.
- https://github.com/crate/cratedb-toolkit/pull/245#pullrequestreview-2262726777
/cc @wierdvanderhaar, @hlcianfagna, @karynzv, @juanpardo, @tomach, @Taliik, @proddata
> Add `quote_relation_name` support utility function

- CHANGES.md
- pyproject.toml
- tests/test_error_handling.py
CrateDB's `error_trace` option has not been respected yet.
- https://github.com/crate/crate-python/pull/648
> Propagate error traces properly, using the `error_trace` `connect_args` option, by using `crate-1.0.0dev1`

- CHANGES.md
- src/sqlalchemy_cratedb/dialect.py
Make the `do_execute...` dialect methods store the last response into the request context instance, to make it available to downstream users.
Code like in cratedb-toolkit will use the response/result, in this case the response from a bulk insert request, to find out about records that failed to insert.
https://github.com/crate/cratedb-toolkit/blob/v0.0.27/cratedb_toolkit/io/core.py#L141-L148
> Slightly amended `do_execute...` dialect methods to store their response

- .github/workflows/nightly.yml
- .github/workflows/tests.yml
GHA updated ubuntu-latest to use Ubuntu 24.04, which apparently dropped supporting Python 3.7.
- GH-164
- GH-165
> CI: Use ubuntu-22.04 to support Python 3.7

- .github/workflows/nightly.yml
- .github/workflows/tests.yml
- CHANGES.md
- pyproject.toml
- tests/bulk_test.py
- tests/integration.py
[Python 3.13.0](https://www.python.org/downloads/release/python-3130/) has been released on Oct. 7, 2024. This PR intends to add CI verification.
- https://github.com/crate/crate-python/pull/653
> CI: Verify support on Python 3.13

- CHANGES.md
- pyproject.toml
- tests/query_caching.py
crate-python 1.0.0 is approaching completion. This patch is one in a series that makes sure everything is in order on the downstream projects.
- https://github.com/crate-workbench/langchain/issues/29
- https://github.com/crate/crash/pull/446
> Dependencies: Update to `crate-1.0.0`

- docs/migrate-from-crate-client.md
The first iteration of this page has been rough. The second one intends to improve the situation.
https://sqlalchemy-cratedb--179.org.readthedocs.build/migrate-from-crate-client.html
Please advise if you think matters can be conveyed better, best using concrete suggestions.
> Documentation: Improve page about migrating to `sqlalchemy-cratedb`

- CHANGES.md
- pyproject.toml
Validate and bring in an improvement to crate-python.
- https://github.com/crate/crate-python/pull/691
- https://github.com/crate/cratedb-toolkit/pull/349
- https://github.com/crate/cloud-api/pull/3038
- https://github.com/crate/stevedore/pull/325
> Update to `crate-2.0.0`, which uses `orjson` for JSON marshalling

- pyproject.toml
The fundamental patch GH-195 needs a little update, pulling in a more recent pre-release version of crate-python.
> Dependencies: Update to `crate>=2.0.0.dev6`

- pyproject.toml
To make GH-199 and subsequent patch release updates for verlib2 obsolete.
> Dependencies: Relax to `verlib2<0.3`

- pyproject.toml
Make GH-209 obsolete.
Here: "validate-pyproject<1"
> Dependencies: Relax version constraints on development tools

- pyproject.toml
- setup.cfg
- src/sqlalchemy_cratedb/compat/core14.py
> Tests: Fix Dask not being installed for testing on Python 3.13
